spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  datasource:
    url: jdbc:h2:mem:mytestdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    user: sa
    password: sa
    driverClassName: org.h2.Driver

axon:
  serializer:
    general: jackson
  eventhandling:
    processors:
      name:
        mode: tracking